all:
	cd MiniSAT/  && make clean

clean:
	rm -f *.o *.{ppu,bak} General/*.{o,ppu,bak} RandomWalk-SATSolver/*.{o,ppu,bak} RWalk-SATSolver/*.{o,ppu,bak} Circuits/*.{o,ppu,bak} Circuits/*/*.{o,ppu,bak}
	cd MiniSAT/  && make clean
